on:
  push:
    branches:
      - master
    paths-ignore: # dont run when changes made to these folders
      - '.vscode/**'
      - 'sandbox/**'
      - 'share/**'
      - 'scripts/**'

jobs:
  extension:
    name: extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch
        run: git fetch --prune --unshallow

      - name: Setup node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Setup yarn
        run: npm i -g yarn

      - name: Setup dependencies
        run: yarn

      - name: Combine markdowns
        run: yarn md:concatenate

      - name: Export version
        id: version
        run: echo "::set-output name=new::1.0.0"

      - name: Use version
        run: echo "${{steps.version.new}}"

      # Update version number

      - name: Build Sources
        run: yarn extension:build

      # - name: Compile VSIX
      #   run: yarn extension:pack

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: vscode-git-commit-3.1.1.vsix
      #     path: ${{github.workspace}}/vscode-git-commit-3.1.1.vsix
